// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAacEJRAtxzFFt5kkHKEV5sYTW7611oBqk',
    appId: '1:111423081142:web:dd9526f5db9853fdc6f417',
    messagingSenderId: '111423081142',
    projectId: 'ismatov-app',
    authDomain: 'ismatov-app.firebaseapp.com',
    storageBucket: 'ismatov-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDioqbF6IIg0K3k-C4k5osPJNEbFzTT3nY',
    appId: '1:111423081142:android:8bba952c3a159223c6f417',
    messagingSenderId: '111423081142',
    projectId: 'ismatov-app',
    storageBucket: 'ismatov-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4fPM62R8wDf0L5uR5OWP9j8G9_rzdu2w',
    appId: '1:111423081142:ios:81c82199ddca0476c6f417',
    messagingSenderId: '111423081142',
    projectId: 'ismatov-app',
    storageBucket: 'ismatov-app.firebasestorage.app',
    iosBundleId: 'com.example.ismatov',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4fPM62R8wDf0L5uR5OWP9j8G9_rzdu2w',
    appId: '1:111423081142:ios:81c82199ddca0476c6f417',
    messagingSenderId: '111423081142',
    projectId: 'ismatov-app',
    storageBucket: 'ismatov-app.firebasestorage.app',
    iosBundleId: 'com.example.ismatov',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAacEJRAtxzFFt5kkHKEV5sYTW7611oBqk',
    appId: '1:111423081142:web:a42d8a6a011be078c6f417',
    messagingSenderId: '111423081142',
    projectId: 'ismatov-app',
    authDomain: 'ismatov-app.firebaseapp.com',
    storageBucket: 'ismatov-app.firebasestorage.app',
  );
}
